{% set name = "colordict" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/colordict-{{ version }}.tar.gz
  sha256: 75854912094196622c7395898c364d0954078f55b32a72d774da739696977dbc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - colordict
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aleferna12/colordict
  summary: A package to allow for easy maintenance of a color dictionary with palettes, so you can use the colors that you like in your different projects.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - carlodri
